name: 'Telegram Message or File Send Action'
description: 'Send a message or files to a Telegram chat with optional Markdown support'
branding:
  icon: 'bell'
  color: 'blue'

inputs:
  bot_token:
    description: 'Telegram Bot Token'
    required: true
  chat_id:
    description: 'Telegram Chat ID'
    required: true
  message:
    description: 'Message to send'
    required: true
  markdown:
    description: 'Enable Markdown parsing'
    required: false
    default: 'false'
  files:
    description: 'Newline-separated list of file paths to send'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Send message or files to Telegram
      shell: bash
      env:
        TELEGRAM_BOT_TOKEN: ${{ inputs.bot_token }}
        TELEGRAM_CHAT_ID: ${{ inputs.chat_id }}
        MESSAGE: ${{ inputs.message }}
        MARKDOWN: ${{ inputs.markdown }}
        FILES: ${{ inputs.files }}
      run: |
        if [ -n "$FILES" ]; then
          echo "$FILES" | while IFS= read -r FILE; do
            echo "Sending file: $FILE"
            curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument \
            -F chat_id=$TELEGRAM_CHAT_ID \
            -F document=@"$FILE" \
            -F caption="$MESSAGE"
          done
        else
          if [ "$MARKDOWN" = "true" ]; then
            PARSE_MODE="-d parse_mode=Markdown"
          else
            PARSE_MODE=""
          fi
          echo "Sending message: $MESSAGE"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
          -d chat_id=$TELEGRAM_CHAT_ID \
          -d text="$MESSAGE" \
          $PARSE_MODE
